// Jenkinsfile
pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-u root' // если нужны права на запись
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'python -m pytest tests/'
            }
        }
    }

    post {
        always {
            cleanWs() // очистка рабочего пространства
        }
    }
}
